// Re-export from auto-generated vehicles-data.ts (generated by 002Aengt pipeline)
export type { Vehicle } from "@/data/vehicles-data";
export { vehicles, filterOptions, getVehicleById, getVehicleBySlug } from "@/data/vehicles-data";
