// Auto-generated by 002Agent pipeline — DO NOT EDIT

export interface Vehicle {
  id: string; slug: string; brand: string; brand_cn: string;
  model: string; model_cn: string;
  year: number;
  mileage_km: number; fuel: string;
  transmission: "manual" | "automatic";
  driving_side: "LHD" | "RHD";
  exterior_color: string; interior_color: string;
  price_cny: number; price_usd: number;
  location: string; description: string;
  vin_last6: string;
  main_image: string; images: string[];
  status: "available" | "sold" | "reserved";
  created_at: string;
  source_folder: string; source_created: string;
}

export const vehicles: Vehicle[] = [
  {
    "id": "v014724",
    "slug": "peugeot-408-2020",
    "brand": "Peugeot",
    "brand_cn": "\u6807\u81f4",
    "model": "408",
    "model_cn": "\u6807\u81f4408",
    "year": 2020,
    "mileage_km": 62000,
    "fuel": "Petrol",
    "transmission": "automatic",
    "driving_side": "LHD",
    "exterior_color": "White",
    "interior_color": "Gray",
    "price_cny": 50000,
    "price_usd": 6944.44,
    "location": "Meishan, Sichuan, China",
    "description": "Well maintained, good condition.",
    "vin_last6": "014724",
    "main_image": "/vehicles/v014724/\u5de6\u524d45\u00b0.webp",
    "images": [
      "/vehicles/v014724/\u5de6\u524d45\u00b0.webp",
      "/vehicles/v014724/01_\u6b63\u524d_\u4e3b\u56fe.webp",
      "/vehicles/v014724/\u524d\u6392\u5185\u9970.webp",
      "/vehicles/v014724/\u53d1\u52a8\u673a\u8231.webp",
      "/vehicles/v014724/\u53f3\u524d45\u00b0.webp",
      "/vehicles/v014724/\u53f3\u540e45\u00b0.webp",
      "/vehicles/v014724/\u540e\u5907\u7bb1.webp",
      "/vehicles/v014724/\u540e\u6392\u5185\u9970.webp",
      "/vehicles/v014724/\u5de6\u540e45\u00b0.webp",
      "/vehicles/v014724/\u6b63\u540e.webp"
    ],
    "status": "available",
    "created_at": "2026-05-28T14:51:22.615+00:00",
    "source_folder": "\ud83d\ude97\u4e58\u7528\u8f66 \u6807\u81f4\u6807\u81f4408 2020\u5e74 \u767d\u8272 6.2\u4e07\u516c\u91cc \u00a54.0\u4e07",
    "source_created": "2026-05-28T14:51:22.615+00:00",
  },
  {
    "id": "v169330",
    "slug": "wuling-hongguang-s-2018",
    "brand": "Wuling",
    "brand_cn": "\u4e94\u83f1",
    "model": "Hongguang S",
    "model_cn": "\u5b8f\u5149S",
    "year": 2018,
    "mileage_km": 85000,
    "fuel": "Petrol",
    "transmission": "manual",
    "driving_side": "LHD",
    "exterior_color": "White",
    "interior_color": "Gray",
    "price_cny": 40000,
    "price_usd": 5555.56,
    "location": "Chengdu, Sichuan, China",
    "description": "Single owner, regularly serviced at authorized dealerships. No accidents, no flood/fire damage. Excellent condition. Third-party inspection welcome.",
    "vin_last6": "",
    "main_image": "/vehicles/v169330/\u5de6\u524d45\u00b0.webp",
    "images": [
      "/vehicles/v169330/\u5de6\u524d45\u00b0.webp",
      "/vehicles/v169330/01_\u6b63\u524d_\u4e3b\u56fe.webp",
      "/vehicles/v169330/\u4e2d\u63a7\u53f0.webp",
      "/vehicles/v169330/\u4eea\u8868\u76d8.webp",
      "/vehicles/v169330/\u53d1\u52a8\u673a\u8231.webp",
      "/vehicles/v169330/\u53f3\u4fa7.webp",
      "/vehicles/v169330/\u53f3\u524d45\u00b0.webp",
      "/vehicles/v169330/\u5de6\u4fa7.webp",
      "/vehicles/v169330/\u6b63\u540e.webp"
    ],
    "status": "available",
    "created_at": "2026-05-27T16:08:09.784Z",
    "source_folder": "\ud83d\ude9b\u5546\u7528\u8f66 \u4e94\u83f1\u5b8f\u5149S 2018\u5e74 \u767d\u8272 8.5\u4e07\u516c\u91cc \u00a53.2\u4e07",
    "source_created": "2026-05-27T16:08:09.784Z",
  }
];

export const filterOptions = {
  brands: ["Peugeot", "Wuling"],
  fuels: ["Petrol"],
  transmissions: ["automatic", "manual"] as const,
};

export function getVehicleById(idOrSlug: string): Vehicle | undefined {
  return vehicles.find(v => v.id === idOrSlug) || vehicles.find(v => v.slug === idOrSlug);
}

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find(v => v.slug === slug);
}
